# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'Trimukesh'
        required: true
        type: string

jobs:
  print-username:
    runs-on: self-hosted

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
